# Generated by Django 2.0.1 on 2018-04-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(default='', max_length=2),
        ),
    ]
