# Generated by Django 2.0.1 on 2018-04-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20180419_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='users',
            field=models.ManyToManyField(to='feed.User'),
        ),
    ]
